# Generated by Django 5.2.4 on 2025-07-18 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('size_chart', models.ImageField(blank=True, null=True, upload_to='size_charts/')),
                ('user_manual', models.FileField(blank=True, null=True, upload_to='user_manuals/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.product')),
            ],
        ),
    ]
